# -*- fill-column: 80; org-confirm-babel-evaluate: nil -*-

#+TITLE:     Assignment 15, Authomata Theory
#+AUTHOR:    Oleg Sivokon
#+EMAIL:     olegsivokon@gmail.com
#+DATE:      <2016-01-01 Fri>
#+DESCRIPTION: Fifth assignment in the course 20440 Automata and Formal Languages
#+KEYWORDS: Automata Theory, Formal Languages, Assignment
#+LANGUAGE: en
#+LaTeX_CLASS: article
#+LATEX_HEADER: \usepackage{commath}
#+LATEX_HEADER: \usepackage{pgf}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usetikzlibrary{shapes,backgrounds}
#+LATEX_HEADER: \usepackage{marginnote}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER: \usepackage{algpseudocode}
#+LATEX_HEADER: \usepackage{algorithm}
#+LATEX_HEADER: \usepackage{mathtools}
#+LATEX_HEADER: \usetikzlibrary{arrows,automata}
#+LATEX_HEADER: \setlength{\parskip}{16pt plus 2pt minus 2pt}
#+LATEX_HEADER: \renewcommand{\arraystretch}{1.6}
#+LATEX_HEADER: \DeclareMathOperator{\Neg}{Neg}

#+BEGIN_SRC emacs-lisp :exports none
  (setq org-latex-pdf-process
        '("latexmk -pdflatex='pdflatex -shell-escape -interaction nonstopmode' -pdf -f %f")
        org-latex-listings t
        org-src-fontify-natively t
        org-latex-custom-lang-environments '((maxima "maxima"))
        org-listings-escape-inside '("(*@" . "@*)")
        org-babel-latex-htlatex "htlatex")

  (defmacro by-backend (&rest body)
    `(cl-case (when (boundp 'backend)
                (org-export-backend-name backend))
       ,@body))
#+END_SRC

#+RESULTS:
: by-backend

#+BEGIN_LATEX
\definecolor{codebg}{rgb}{0.96,0.99,0.8}
\definecolor{codestr}{rgb}{0.46,0.09,0.2}
\lstset{%
  backgroundcolor=\color{codebg},
  basicstyle=\ttfamily\scriptsize,
  breakatwhitespace=false,
  breaklines=false,
  captionpos=b,
  framexleftmargin=10pt,
  xleftmargin=10pt,
  framerule=0pt,
  frame=tb,
  keepspaces=true,
  keywordstyle=\color{blue},
  showspaces=false,
  showstringspaces=false,
  showtabs=false,
  stringstyle=\color{codestr},
  tabsize=2
}
\lstnewenvironment{maxima}{%
  \lstset{%
    backgroundcolor=\color{codebg},
    escapeinside={(*@}{@*)},
    aboveskip=20pt,
    captionpos=b,
    label=,
    caption=,
    showstringspaces=false,
    frame=single,
    framerule=0pt,
    basicstyle=\ttfamily\scriptsize,
    columns=fixed}}{}
}
\makeatletter
\newcommand{\verbatimfont}[1]{\renewcommand{\verbatim@font}{\ttfamily#1}}
\makeatother
\verbatimfont{\small}%
\clearpage
#+END_LATEX

* Problems

** Problem 1
   Given context-free grammar $V = \{S,M,N,W,X,Y,Z\}$ s.t. $T=\{1,0\}$
   
   #+HEADER: :exports results
   #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
   #+BEGIN_SRC latex
     \begin{align*}
       &S \to M \;|\; XN \;|\; W \;|\; 0N \;|\; 1Z1 \\
       &M \to 0M0 \;|\; N \\
       &N \to N0 \;|\; 0 \\
       &W \to 0W \;|\; 00W0 \\
       &X \to 0X1 \;|\; 0 \;|\; 0Y0 \\
       &Z \to W \;.
     \end{align*}
   #+END_SRC
   
   1. Is $V$ ambiguous?
   2. Give a normalized grammar equivalent to $V$.

*** Answer 2
    It is easier to normalize the grammar first and then to look for ambiguities,
    thus the answers are in reverse order.
    1. Any derivation containing $W$ cannot terminate, and so does $Z$.
    2. Further, we can eliminate the rule $M \to N$.
    3. $Y$ has no derivation rules, thus we can also remove it.
       
    Thus obtaining:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{align*}
        &S \to M \;|\; XM \;|\; 0M \\
        &M \to 0M0 \;|\; 0 \;|\; 0M \\
        &X \to 0X1 \;|\; 0 \;.
      \end{align*}
    #+END_SRC

    1. It is easy to see that $M$ derives number of zeros greater than one,
       thus $M \to 0M0$ is redundant.  Subsequently, $S \to 0M$ is already
       covered by $S \to M$.
       
       
    What remains is:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{align*}
        &S \to M \;|\; XM \\
        &M \to 0 \;|\; 0M \\
        &X \to 0 \;|\; 0X1 \;.
      \end{align*}
    #+END_SRC

*** Answer 1
    Now it is easy to see that the string 00 can be derived in two different
    ways:

    + $S \to M$, $M \to 0M$, $M \to 0$.
    + $S \to XM$, $X \to 0$, $M \to 0$.
      
    Hence $V$ is ambiguous.
